// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hoyeonUM/golang-example/example_gorutine (interfaces: HttpClient)

// Package mock_example_gorutine is a generated GoMock package.
package mock_example_gorutine

import (
	gomock "github.com/golang/mock/gomock"
	example_gorutine "github.com/hoyeonUM/golang-example/example_gorutine"
	reflect "reflect"
)

// MockHttpClient is a mock of HttpClient interface
type MockHttpClient struct {
	ctrl     *gomock.Controller
	recorder *MockHttpClientMockRecorder
}

// MockHttpClientMockRecorder is the mock recorder for MockHttpClient
type MockHttpClientMockRecorder struct {
	mock *MockHttpClient
}

// NewMockHttpClient creates a new mock instance
func NewMockHttpClient(ctrl *gomock.Controller) *MockHttpClient {
	mock := &MockHttpClient{ctrl: ctrl}
	mock.recorder = &MockHttpClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHttpClient) EXPECT() *MockHttpClientMockRecorder {
	return m.recorder
}

// Request mocks base method
func (m *MockHttpClient) Request(arg0 string, arg1 chan example_gorutine.HttpResponse) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Request", arg0, arg1)
}

// Request indicates an expected call of Request
func (mr *MockHttpClientMockRecorder) Request(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockHttpClient)(nil).Request), arg0, arg1)
}
